### ISSUE TITLE
iterator have no attribute of 'remove' and 'len'!

### ISSUE THREAD

**Issue by fooSynaptic** [keiichishima/pcalg#2]
I was trying to use pc-algorithm use your script, but i encounter error below immediately:

`File "pcalg.py", line 72, in estimate_skeleton
    adj_i.remove(j)
AttributeError: 'dict_keyiterator' object has no attribute 'remove'
`
for the adj_i was G neighbors of node i(G was a graph).
it seems the adj_i was a iterator. how it could be an object of remove and len?
can you tell me how to correctly use this module?

**Comment by keiichishima** [comment]
Thank you for reporting this issue.

I checked the code and underlying libraries, and found that the version bump of the networkx module from 1.11 to 2.0 caused this issue.

I think I've fixed this issue.  Please use the latest version of this module.

**Comment by fooSynaptic** [comment]
Thank you! It works well now.
